/**
 * categories.ts
 * Single Source of Truth for Automotive Categories across the entire Mobile App.
 * Matches SellPartScreen, EditListingScreen, HomeScreen, and AllCategoriesScreen.
 */

export interface MasterCategory {
  id: string;
  name: string;
  icon: string;
  bg: string;
  color: string;
  description: string;
  popularParts: string[];
  is3DGraphic?: string;
}

export const MASTER_CATEGORIES: MasterCategory[] = [
  {
    id: 'Engine & Mechanical',
    name: 'Engine & Mechanical',
    icon: 'engine',
    bg: '#FEF2F2',
    color: '#DC2626',
    description: 'Engines, cylinder heads, pistons, turbochargers, alternators & starters',
    popularParts: [
      'Complete Engine Assembly',
      'Cylinder Head',
      'Piston & Connecting Rods',
      'Turbocharger / Intercooler',
      'Alternator',
      'Starter Motor',
    ],
    is3DGraphic: 'engine',
  },
  {
    id: 'Body & Exterior',
    name: 'Body & Exterior',
    icon: 'car-door',
    bg: '#F0F9FF',
    color: '#0284C7',
    description: 'Bumpers, bonnets, grilles, doors, fenders, boot lids & mirrors',
    popularParts: [
      'Front Bumper Assembly',
      'Rear Bumper Assembly',
      'Bonnet / Hood',
      'Front Grille',
      'Side Mirror Assembly (ORVM)',
      'Front / Rear Doors',
    ],
    is3DGraphic: 'body',
  },
  {
    id: 'Lights & Electricals',
    name: 'Lights & Electricals',
    icon: 'lightning-bolt',
    bg: '#FEFCE8',
    color: '#D97706',
    description: 'Headlights, tail lights, fog lamps, ECU/ECM, wiring harnesses & batteries',
    popularParts: [
      'Headlight Assembly (Pair/Single)',
      'Tail Light Assembly',
      'Fog Lamps / DRLs',
      'Engine Control Unit (ECU / ECM)',
      'Complete Wiring Harness',
      'Car Battery',
    ],
    is3DGraphic: 'electrical',
  },
  {
    id: 'Suspension & Brakes',
    name: 'Suspension & Brakes',
    icon: 'car-brake-alert',
    bg: '#FFF1F2',
    color: '#E11D48',
    description: 'Shock absorbers, struts, brake calipers, disc rotors & steering racks',
    popularParts: [
      'Front Shock Absorbers (Struts)',
      'Rear Shock Absorbers',
      'Brake Calipers (Front/Rear)',
      'Brake Disc Rotors / Drums',
      'Steering Rack & Pinion Assembly',
      'ABS Pump / Module',
    ],
    is3DGraphic: 'suspension',
  },
  {
    id: 'Interior & Wheels',
    name: 'Interior & Wheels',
    icon: 'car-seat',
    bg: '#FAF5FF',
    color: '#7C3AED',
    description: 'Dashboards, steering wheels, alloy wheels, seats & infotainment screens',
    popularParts: [
      'Complete Dashboard Assembly',
      'Steering Wheel with Airbag',
      'Alloy Wheels (Set / Single)',
      'Seat Assembly (Front/Rear)',
      'Touchscreen Infotainment Screen',
      'Spare Tyre / Rim',
    ],
    is3DGraphic: 'interior',
  },
  {
    id: 'Cooling & AC',
    name: 'Cooling & AC',
    icon: 'fan',
    bg: '#F0FDFA',
    color: '#0D9488',
    description: 'AC compressors, cooling radiators, condensers, blower motors & fans',
    popularParts: [
      'AC Compressor',
      'AC Condenser',
      'Cooling Radiator',
      'Radiator Cooling Fan Assembly',
      'Heating Core / Blower Motor',
    ],
    is3DGraphic: 'cooling',
  },
  {
    id: 'Transmission & Clutch',
    name: 'Transmission & Clutch',
    icon: 'car-shift-pattern',
    bg: '#EFF6FF',
    color: '#2563EB',
    description: 'Manual/automatic gearboxes, clutch plates, flywheels & drive shafts',
    popularParts: [
      'Manual Gearbox Assembly',
      'Automatic Transmission (AT/CVT/DCT)',
      'Clutch Plate & Pressure Plate',
      'Flywheel (Dual Mass / Single)',
      'Drive Shaft / Axle',
    ],
    is3DGraphic: 'transmission',
  },
  {
    id: 'Exhaust & Fuel',
    name: 'Exhaust & Fuel',
    icon: 'pipe',
    bg: '#ECFDF5',
    color: '#059669',
    description: 'Catalytic converters, mufflers, exhaust manifolds, fuel tanks & EGR valves',
    popularParts: [
      'Catalytic Converter / DPF',
      'Exhaust Manifold & Muffler',
      'Fuel Tank Assembly',
      'EGR Valve',
      'Fuel Pump (High/Low Pressure)',
    ],
    is3DGraphic: 'exhaust',
  },
];

export const MASTER_CATEGORY_PARTS: Record<string, string[]> = {
  'Engine & Mechanical': [
    'Complete Engine Assembly',
    'Cylinder Head',
    'Piston & Connecting Rods',
    'Crankshaft & Camshaft',
    'Turbocharger / Intercooler',
    'Alternator',
    'Starter Motor',
    'Fuel Injectors / Rail',
    'Fuel Pump (High/Low Pressure)',
    'Oil Pump & Sump',
    'Timing Belt / Chain Kit',
    'Engine Mountings',
    'Throttle Body / Air Intake',
  ],
  'Body & Exterior': [
    'Front Bumper Assembly',
    'Rear Bumper Assembly',
    'Bonnet / Hood',
    'Front Grille',
    'Headlight Assembly (Pair/Single)',
    'Tail Light Assembly',
    'Fog Lamps / DRLs',
    'Side Mirror Assembly (ORVM)',
    'Front / Rear Doors',
    'Fenders / Quarter Panels',
    'Boot Lid / Tailgate',
    'Windshield Glass (Front/Rear)',
    'Door Handles & Locks',
  ],
  'Lights & Electricals': [
    'Engine Control Unit (ECU / ECM)',
    'Body Control Module (BCM)',
    'Complete Wiring Harness',
    'Instrument Cluster / Speedometer',
    'Fuse Box & Relays',
    'Key Fob / Immobilizer System',
    'Sensors (Oxygen, MAP, ABS, Cam)',
    'Car Battery',
    'Headlight Switch / Stalk',
  ],
  'Suspension & Brakes': [
    'Front Shock Absorbers (Struts)',
    'Rear Shock Absorbers',
    'Brake Calipers (Front/Rear)',
    'Brake Disc Rotors / Drums',
    'Brake Booster & Master Cylinder',
    'ABS Pump / Module',
    'Lower Control Arms',
    'Steering Rack & Pinion Assembly',
    'Power Steering Pump',
    'Anti-Roll / Sway Bar',
    'Wheel Hub & Bearings',
  ],
  'Interior & Wheels': [
    'Complete Dashboard Assembly',
    'Steering Wheel with Airbag',
    'Airbag Module (Driver/Passenger)',
    'Seat Assembly (Front/Rear)',
    'Touchscreen Infotainment Screen',
    'AC Vents & Controls Panel',
    'Power Window Motor / Switches',
    'Alloy Wheels (Set / Single)',
    'Spare Tyre / Rim',
  ],
  'Cooling & AC': [
    'AC Compressor',
    'AC Condenser',
    'Cooling Radiator',
    'Radiator Cooling Fan Assembly',
    'Intercooler',
    'Heating Core / Blower Motor',
    'Thermostat & Housing',
    'Coolant Reservoir Tank',
  ],
  'Transmission & Clutch': [
    'Manual Gearbox Assembly',
    'Automatic Transmission (AT/CVT/DCT)',
    'Clutch Plate & Pressure Plate',
    'Flywheel (Dual Mass / Single)',
    'Drive Shaft / Axle',
    'Clutch Master & Slave Cylinder',
    'Differential Assembly',
  ],
  'Exhaust & Fuel': [
    'Catalytic Converter / DPF',
    'Exhaust Manifold & Muffler',
    'Fuel Tank Assembly',
    'EGR Valve',
    'Exhaust Pipe & Resonator',
  ],
};
